-- PostgreSQL schema draft for TeleRoute.
-- Stage 9 artifact only: DDL draft, no seed data, no runtime switch.
-- Source: app/schema.sql as of this branch.

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL,
    email TEXT,
    display_name TEXT NOT NULL,
    role_key TEXT NOT NULL DEFAULT 'operator',
    role TEXT,
    must_change_password BOOLEAN NOT NULL DEFAULT false,
    is_active BOOLEAN NOT NULL DEFAULT true,
    password_hash TEXT,
    password_salt TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_users_username UNIQUE (username)
);


CREATE TABLE IF NOT EXISTS demo_data_state (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS user_permissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    section_key TEXT NOT NULL,
    can_read BOOLEAN NOT NULL DEFAULT false,
    can_write BOOLEAN NOT NULL DEFAULT false,
    can_export BOOLEAN NOT NULL DEFAULT false,
    CONSTRAINT fk_user_permissions_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT uq_user_permissions_user_section UNIQUE (user_id, section_key)
);

CREATE TABLE IF NOT EXISTS countries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    code TEXT,
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_countries_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS currencies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT NOT NULL,
    name TEXT NOT NULL,
    symbol TEXT,
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_currencies_code UNIQUE (code)
);

CREATE TABLE IF NOT EXISTS currency_rates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    currency_id BIGINT NOT NULL,
    rate_to_eur NUMERIC(20,8) NOT NULL,
    rate_date DATE NOT NULL,
    updated_by BIGINT NOT NULL,
    comment TEXT,
    source TEXT NOT NULL DEFAULT 'manual',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_currency_rates_currency FOREIGN KEY (currency_id) REFERENCES currencies(id) ON DELETE RESTRICT,
    CONSTRAINT fk_currency_rates_updated_by FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE RESTRICT,
    CONSTRAINT ck_currency_rates_rate_positive CHECK (rate_to_eur > 0),
    CONSTRAINT ck_currency_rates_source CHECK (source IN ('manual', 'api', 'import'))
);

CREATE TABLE IF NOT EXISTS providers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    normalized_name TEXT NOT NULL,
    provider_type TEXT NOT NULL DEFAULT 'unknown',
    default_currency_id BIGINT,
    is_active BOOLEAN NOT NULL DEFAULT true,
    comment TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_providers_normalized_name UNIQUE (normalized_name),
    CONSTRAINT fk_providers_default_currency FOREIGN KEY (default_currency_id) REFERENCES currencies(id) ON DELETE RESTRICT,
    CONSTRAINT ck_providers_provider_type CHECK (provider_type IN ('voip', 'sms', 'gateway', 'other', 'unknown'))
);

CREATE TABLE IF NOT EXISTS provider_prefixes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_id BIGINT NOT NULL,
    prefix TEXT,
    name TEXT,
    comment TEXT,
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_provider_prefixes_provider FOREIGN KEY (provider_id) REFERENCES providers(id) ON DELETE RESTRICT
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_provider_prefixes_provider_prefix
    ON provider_prefixes(provider_id, COALESCE(prefix, ''));

CREATE TABLE IF NOT EXISTS routes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    country_id BIGINT NOT NULL,
    provider_id BIGINT NOT NULL,
    provider_prefix_id BIGINT,
    name TEXT NOT NULL,
    project_label TEXT,
    cli_source_type TEXT NOT NULL,
    cli_source_label TEXT NOT NULL,
    aon_pool TEXT,
    rnd_type TEXT,
    rnd_pool_owner TEXT,
    comment TEXT,
    is_actual BOOLEAN NOT NULL DEFAULT true,
    priority_status TEXT NOT NULL DEFAULT 'unknown',
    inbound_line_available BOOLEAN NOT NULL DEFAULT false,
    created_by BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_by BIGINT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_routes_country FOREIGN KEY (country_id) REFERENCES countries(id) ON DELETE RESTRICT,
    CONSTRAINT fk_routes_provider FOREIGN KEY (provider_id) REFERENCES providers(id) ON DELETE RESTRICT,
    CONSTRAINT fk_routes_provider_prefix FOREIGN KEY (provider_prefix_id) REFERENCES provider_prefixes(id) ON DELETE RESTRICT,
    CONSTRAINT fk_routes_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE RESTRICT,
    CONSTRAINT fk_routes_updated_by FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE RESTRICT,
    CONSTRAINT uq_routes_country_name UNIQUE (country_id, name),
    CONSTRAINT ck_routes_cli_source_type CHECK (cli_source_type IN ('rnd', 'pool', 'sim', 'single_number', 'other')),
    CONSTRAINT ck_routes_rnd_type CHECK (rnd_type IN ('local', 'nonlocal') OR rnd_type IS NULL),
    CONSTRAINT ck_routes_priority_status CHECK (priority_status IN ('priority', 'alternative', 'normal', 'unknown'))
);

CREATE TABLE IF NOT EXISTS route_naming_rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    template TEXT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT false,
    comment TEXT,
    created_by BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_by BIGINT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_route_naming_rules_name UNIQUE (name),
    CONSTRAINT fk_route_naming_rules_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE RESTRICT,
    CONSTRAINT fk_route_naming_rules_updated_by FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE RESTRICT
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_route_naming_rules_single_active
    ON route_naming_rules(is_active) WHERE is_active IS TRUE;

CREATE TABLE IF NOT EXISTS tariffs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    country_id BIGINT NOT NULL,
    provider_id BIGINT NOT NULL,
    provider_prefix_id BIGINT,
    provider_currency_id BIGINT NOT NULL,
    price_in_provider_currency NUMERIC(18,6) NOT NULL,
    conversion_rate_to_eur NUMERIC(20,8) NOT NULL,
    conversion_rate_date DATE NOT NULL,
    currency_rate_id BIGINT,
    eur_price NUMERIC(18,6) NOT NULL,
    priority_status TEXT NOT NULL DEFAULT 'unknown',
    is_estimated BOOLEAN NOT NULL DEFAULT false,
    comment TEXT,
    valid_from TIMESTAMPTZ,
    valid_to TIMESTAMPTZ,
    is_current BOOLEAN NOT NULL DEFAULT true,
    created_by BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_by BIGINT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_tariffs_country FOREIGN KEY (country_id) REFERENCES countries(id) ON DELETE RESTRICT,
    CONSTRAINT fk_tariffs_provider FOREIGN KEY (provider_id) REFERENCES providers(id) ON DELETE RESTRICT,
    CONSTRAINT fk_tariffs_provider_prefix FOREIGN KEY (provider_prefix_id) REFERENCES provider_prefixes(id) ON DELETE RESTRICT,
    CONSTRAINT fk_tariffs_provider_currency FOREIGN KEY (provider_currency_id) REFERENCES currencies(id) ON DELETE RESTRICT,
    CONSTRAINT fk_tariffs_currency_rate FOREIGN KEY (currency_rate_id) REFERENCES currency_rates(id) ON DELETE RESTRICT,
    CONSTRAINT fk_tariffs_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE RESTRICT,
    CONSTRAINT fk_tariffs_updated_by FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE RESTRICT,
    CONSTRAINT ck_tariffs_price_nonnegative CHECK (price_in_provider_currency >= 0),
    CONSTRAINT ck_tariffs_conversion_rate_positive CHECK (conversion_rate_to_eur > 0),
    CONSTRAINT ck_tariffs_eur_price_nonnegative CHECK (eur_price >= 0),
    CONSTRAINT ck_tariffs_priority_status CHECK (priority_status IN ('priority', 'alternative', 'normal', 'unknown'))
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_tariffs_current_business_key
    ON tariffs(country_id, provider_id, COALESCE(provider_prefix_id, 0)) WHERE is_current IS TRUE;

CREATE TABLE IF NOT EXISTS tariff_change_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tariff_id BIGINT NOT NULL,
    changed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    changed_by BIGINT NOT NULL,
    country_id BIGINT,
    country_name_snapshot TEXT NOT NULL,
    provider_id BIGINT,
    provider_name_snapshot TEXT NOT NULL,
    provider_prefix_id BIGINT,
    prefix_snapshot TEXT,
    old_provider_currency_id BIGINT,
    new_provider_currency_id BIGINT NOT NULL,
    old_price_in_provider_currency NUMERIC(18,6),
    new_price_in_provider_currency NUMERIC(18,6) NOT NULL,
    old_conversion_rate_to_eur NUMERIC(20,8),
    new_conversion_rate_to_eur NUMERIC(20,8) NOT NULL,
    old_conversion_rate_date DATE,
    new_conversion_rate_date DATE NOT NULL,
    old_eur_price NUMERIC(18,6),
    new_eur_price NUMERIC(18,6) NOT NULL,
    eur_price_delta NUMERIC(18,6),
    reason TEXT,
    comment TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_tariff_change_history_tariff FOREIGN KEY (tariff_id) REFERENCES tariffs(id) ON DELETE RESTRICT,
    CONSTRAINT fk_tariff_change_history_changed_by FOREIGN KEY (changed_by) REFERENCES users(id) ON DELETE RESTRICT,
    CONSTRAINT fk_tariff_change_history_country FOREIGN KEY (country_id) REFERENCES countries(id) ON DELETE RESTRICT,
    CONSTRAINT fk_tariff_change_history_provider FOREIGN KEY (provider_id) REFERENCES providers(id) ON DELETE RESTRICT,
    CONSTRAINT fk_tariff_change_history_prefix FOREIGN KEY (provider_prefix_id) REFERENCES provider_prefixes(id) ON DELETE RESTRICT,
    CONSTRAINT fk_tariff_change_history_old_currency FOREIGN KEY (old_provider_currency_id) REFERENCES currencies(id) ON DELETE RESTRICT,
    CONSTRAINT fk_tariff_change_history_new_currency FOREIGN KEY (new_provider_currency_id) REFERENCES currencies(id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS phone_numbers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    country_id BIGINT NOT NULL,
    provider_id BIGINT,
    country_label TEXT,
    provider_label TEXT,
    number TEXT NOT NULL,
    normalized_number TEXT NOT NULL,
    project_label TEXT,
    assignment_type TEXT,
    assignment_label TEXT,
    phone_type TEXT,
    tariff_label TEXT,
    status TEXT NOT NULL DEFAULT 'unknown',
    connection_cost NUMERIC(18,6),
    monthly_fee NUMERIC(18,6),
    outgoing_rate NUMERIC(18,6),
    incoming_rate NUMERIC(18,6),
    currency_id BIGINT,
    currency_label TEXT,
    comment TEXT,
    is_active BOOLEAN NOT NULL DEFAULT true,
    review_required BOOLEAN NOT NULL DEFAULT false,
    imported_created_by TEXT,
    created_by BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_by BIGINT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deactivated_at TIMESTAMPTZ,
    CONSTRAINT uq_phone_numbers_normalized_number UNIQUE (normalized_number),
    CONSTRAINT fk_phone_numbers_country FOREIGN KEY (country_id) REFERENCES countries(id) ON DELETE RESTRICT,
    CONSTRAINT fk_phone_numbers_provider FOREIGN KEY (provider_id) REFERENCES providers(id) ON DELETE RESTRICT,
    CONSTRAINT fk_phone_numbers_currency FOREIGN KEY (currency_id) REFERENCES currencies(id) ON DELETE RESTRICT,
    CONSTRAINT fk_phone_numbers_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE RESTRICT,
    CONSTRAINT fk_phone_numbers_updated_by FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE RESTRICT,
    CONSTRAINT ck_phone_numbers_status CHECK (status IN ('used', 'unused', 'free', 'problem', 'unknown')),
    CONSTRAINT ck_phone_numbers_costs_nonnegative CHECK ((connection_cost IS NULL OR connection_cost >= 0) AND (monthly_fee IS NULL OR monthly_fee >= 0) AND (outgoing_rate IS NULL OR outgoing_rate >= 0) AND (incoming_rate IS NULL OR incoming_rate >= 0)),
    CONSTRAINT ck_phone_numbers_number_format CHECK (number ~ '^[1-9][0-9]{6,20}$'),
    CONSTRAINT ck_phone_numbers_normalized_matches CHECK (normalized_number = number)
);

CREATE TABLE IF NOT EXISTS route_phone_numbers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    route_id BIGINT NOT NULL,
    phone_number_id BIGINT NOT NULL,
    usage_type TEXT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT true,
    added_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    removed_at TIMESTAMPTZ,
    added_by BIGINT NOT NULL,
    removed_by BIGINT,
    comment TEXT,
    CONSTRAINT fk_route_phone_numbers_route FOREIGN KEY (route_id) REFERENCES routes(id) ON DELETE RESTRICT,
    CONSTRAINT fk_route_phone_numbers_phone_number FOREIGN KEY (phone_number_id) REFERENCES phone_numbers(id) ON DELETE RESTRICT,
    CONSTRAINT fk_route_phone_numbers_added_by FOREIGN KEY (added_by) REFERENCES users(id) ON DELETE RESTRICT,
    CONSTRAINT fk_route_phone_numbers_removed_by FOREIGN KEY (removed_by) REFERENCES users(id) ON DELETE RESTRICT,
    CONSTRAINT ck_route_phone_numbers_usage_type CHECK (usage_type IN ('cli', 'pool_member', 'main_number', 'backup_number', 'inbound_line', 'office_phone', 'sim_card', 'other'))
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_route_phone_numbers_active_link
    ON route_phone_numbers(route_id, phone_number_id) WHERE is_active IS TRUE;

CREATE TABLE IF NOT EXISTS route_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    route_id BIGINT NOT NULL,
    action TEXT NOT NULL,
    changed_by BIGINT NOT NULL,
    changed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    field_name TEXT,
    old_value TEXT,
    new_value TEXT,
    reason TEXT,
    comment TEXT,
    CONSTRAINT fk_route_history_route FOREIGN KEY (route_id) REFERENCES routes(id) ON DELETE RESTRICT,
    CONSTRAINT fk_route_history_changed_by FOREIGN KEY (changed_by) REFERENCES users(id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS phone_number_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phone_number_id BIGINT NOT NULL,
    action TEXT NOT NULL,
    changed_by BIGINT NOT NULL,
    changed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    field_name TEXT,
    old_value TEXT,
    new_value TEXT,
    reason TEXT,
    comment TEXT,
    CONSTRAINT fk_phone_number_history_phone_number FOREIGN KEY (phone_number_id) REFERENCES phone_numbers(id) ON DELETE RESTRICT,
    CONSTRAINT fk_phone_number_history_changed_by FOREIGN KEY (changed_by) REFERENCES users(id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS route_phone_number_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    route_id BIGINT NOT NULL,
    phone_number_id BIGINT,
    old_phone_number_id BIGINT,
    new_phone_number_id BIGINT,
    action TEXT NOT NULL,
    changed_by BIGINT NOT NULL,
    changed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    old_values TEXT,
    new_values TEXT,
    reason TEXT,
    comment TEXT,
    CONSTRAINT fk_route_phone_number_history_route FOREIGN KEY (route_id) REFERENCES routes(id) ON DELETE RESTRICT,
    CONSTRAINT fk_route_phone_number_history_phone_number FOREIGN KEY (phone_number_id) REFERENCES phone_numbers(id) ON DELETE RESTRICT,
    CONSTRAINT fk_route_phone_number_history_old_phone_number FOREIGN KEY (old_phone_number_id) REFERENCES phone_numbers(id) ON DELETE RESTRICT,
    CONSTRAINT fk_route_phone_number_history_new_phone_number FOREIGN KEY (new_phone_number_id) REFERENCES phone_numbers(id) ON DELETE RESTRICT,
    CONSTRAINT fk_route_phone_number_history_changed_by FOREIGN KEY (changed_by) REFERENCES users(id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS servers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    comment TEXT,
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_servers_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS phone_number_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT true,
    comment TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_phone_number_types_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT,
    name TEXT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT true,
    sort_order INTEGER NOT NULL DEFAULT 0,
    include_in_route_name BOOLEAN NOT NULL DEFAULT true,
    comment TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_projects_code UNIQUE (code),
    CONSTRAINT uq_projects_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS phone_assignment_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT NOT NULL,
    name TEXT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT true,
    sort_order INTEGER NOT NULL DEFAULT 0,
    comment TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_phone_assignment_types_code UNIQUE (code),
    CONSTRAINT uq_phone_assignment_types_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS calling_companies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    server_id BIGINT NOT NULL,
    country_id BIGINT NOT NULL,
    company_name TEXT NOT NULL,
    company_id_external TEXT NOT NULL,
    has_autorotation BOOLEAN NOT NULL DEFAULT false,
    line_count INTEGER NOT NULL DEFAULT 0,
    dial_set_count INTEGER NOT NULL DEFAULT 0,
    retry_interval_seconds INTEGER NOT NULL DEFAULT 0,
    comment TEXT,
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_by BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_by BIGINT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_calling_companies_server FOREIGN KEY (server_id) REFERENCES servers(id) ON DELETE RESTRICT,
    CONSTRAINT fk_calling_companies_country FOREIGN KEY (country_id) REFERENCES countries(id) ON DELETE RESTRICT,
    CONSTRAINT fk_calling_companies_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE RESTRICT,
    CONSTRAINT fk_calling_companies_updated_by FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE RESTRICT,
    CONSTRAINT uq_calling_companies_server_country_external UNIQUE (server_id, country_id, company_id_external),
    CONSTRAINT ck_calling_companies_external_nonblank CHECK (length(trim(company_id_external)) > 0),
    CONSTRAINT ck_calling_companies_counts_nonnegative CHECK (line_count >= 0 AND dial_set_count >= 0 AND retry_interval_seconds >= 0)
);

CREATE TABLE IF NOT EXISTS company_routing_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    calling_company_id BIGINT NOT NULL,
    country_id BIGINT NOT NULL,
    server_id BIGINT NOT NULL,
    route_id BIGINT,
    routing_mode TEXT NOT NULL,
    has_autorotation BOOLEAN NOT NULL DEFAULT false,
    is_active BOOLEAN NOT NULL DEFAULT true,
    comment TEXT,
    valid_from TIMESTAMPTZ NOT NULL DEFAULT now(),
    valid_to TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by BIGINT NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_by BIGINT,
    CONSTRAINT fk_company_routing_settings_company FOREIGN KEY (calling_company_id) REFERENCES calling_companies(id) ON DELETE RESTRICT,
    CONSTRAINT fk_company_routing_settings_country FOREIGN KEY (country_id) REFERENCES countries(id) ON DELETE RESTRICT,
    CONSTRAINT fk_company_routing_settings_server FOREIGN KEY (server_id) REFERENCES servers(id) ON DELETE RESTRICT,
    CONSTRAINT fk_company_routing_settings_route FOREIGN KEY (route_id) REFERENCES routes(id) ON DELETE RESTRICT,
    CONSTRAINT fk_company_routing_settings_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE RESTRICT,
    CONSTRAINT fk_company_routing_settings_updated_by FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE RESTRICT,
    CONSTRAINT ck_company_routing_settings_mode CHECK (routing_mode IN ('server_priority', 'campaign_route', 'autorotation', 'mixed')),
    CONSTRAINT ck_company_routing_settings_active_valid_to CHECK ((is_active IS TRUE AND valid_to IS NULL) OR is_active IS FALSE)
);

CREATE TABLE IF NOT EXISTS change_reasons (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_change_reasons_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS provider_change_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    changed_at TIMESTAMPTZ NOT NULL,
    country_id BIGINT NOT NULL,
    company_id BIGINT,
    company_name_snapshot TEXT,
    has_autorotation_snapshot BOOLEAN,
    route_before_id BIGINT,
    provider_before_id BIGINT NOT NULL,
    provider_prefix_before_id BIGINT,
    tariff_before_id BIGINT,
    price_before_provider_currency_id BIGINT,
    price_before_in_provider_currency NUMERIC(18,6),
    price_before_conversion_rate_to_eur NUMERIC(20,8),
    price_before_conversion_rate_date DATE,
    price_before_eur NUMERIC(18,6),
    route_after_id BIGINT,
    provider_after_id BIGINT NOT NULL,
    provider_prefix_after_id BIGINT,
    tariff_after_id BIGINT,
    price_after_provider_currency_id BIGINT,
    price_after_in_provider_currency NUMERIC(18,6),
    price_after_conversion_rate_to_eur NUMERIC(20,8),
    price_after_conversion_rate_date DATE,
    price_after_eur NUMERIC(18,6),
    price_delta_eur NUMERIC(18,6),
    provider_changed BOOLEAN NOT NULL,
    reason_id BIGINT,
    reason_text TEXT,
    comment TEXT,
    telegram_status TEXT NOT NULL DEFAULT 'not_sent',
    telegram_sent_at TIMESTAMPTZ,
    created_by BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_by BIGINT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_provider_change_logs_country FOREIGN KEY (country_id) REFERENCES countries(id) ON DELETE RESTRICT,
    CONSTRAINT fk_provider_change_logs_company FOREIGN KEY (company_id) REFERENCES calling_companies(id) ON DELETE RESTRICT,
    CONSTRAINT fk_provider_change_logs_route_before FOREIGN KEY (route_before_id) REFERENCES routes(id) ON DELETE RESTRICT,
    CONSTRAINT fk_provider_change_logs_provider_before FOREIGN KEY (provider_before_id) REFERENCES providers(id) ON DELETE RESTRICT,
    CONSTRAINT fk_provider_change_logs_prefix_before FOREIGN KEY (provider_prefix_before_id) REFERENCES provider_prefixes(id) ON DELETE RESTRICT,
    CONSTRAINT fk_provider_change_logs_tariff_before FOREIGN KEY (tariff_before_id) REFERENCES tariffs(id) ON DELETE RESTRICT,
    CONSTRAINT fk_provider_change_logs_price_before_currency FOREIGN KEY (price_before_provider_currency_id) REFERENCES currencies(id) ON DELETE RESTRICT,
    CONSTRAINT fk_provider_change_logs_route_after FOREIGN KEY (route_after_id) REFERENCES routes(id) ON DELETE RESTRICT,
    CONSTRAINT fk_provider_change_logs_provider_after FOREIGN KEY (provider_after_id) REFERENCES providers(id) ON DELETE RESTRICT,
    CONSTRAINT fk_provider_change_logs_prefix_after FOREIGN KEY (provider_prefix_after_id) REFERENCES provider_prefixes(id) ON DELETE RESTRICT,
    CONSTRAINT fk_provider_change_logs_tariff_after FOREIGN KEY (tariff_after_id) REFERENCES tariffs(id) ON DELETE RESTRICT,
    CONSTRAINT fk_provider_change_logs_price_after_currency FOREIGN KEY (price_after_provider_currency_id) REFERENCES currencies(id) ON DELETE RESTRICT,
    CONSTRAINT fk_provider_change_logs_reason FOREIGN KEY (reason_id) REFERENCES change_reasons(id) ON DELETE RESTRICT,
    CONSTRAINT fk_provider_change_logs_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE RESTRICT,
    CONSTRAINT fk_provider_change_logs_updated_by FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE RESTRICT,
    CONSTRAINT ck_provider_change_logs_telegram_status CHECK (telegram_status IN ('not_sent', 'sent', 'failed', 'disabled'))
);

CREATE TABLE IF NOT EXISTS provider_change_log_servers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_change_log_id BIGINT NOT NULL,
    server_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_provider_change_log_servers_log FOREIGN KEY (provider_change_log_id) REFERENCES provider_change_logs(id) ON DELETE CASCADE,
    CONSTRAINT fk_provider_change_log_servers_server FOREIGN KEY (server_id) REFERENCES servers(id) ON DELETE RESTRICT,
    CONSTRAINT uq_provider_change_log_servers_log_server UNIQUE (provider_change_log_id, server_id)
);

CREATE TABLE IF NOT EXISTS server_route_priorities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    country_id BIGINT NOT NULL,
    server_id BIGINT NOT NULL,
    current_route_id BIGINT NOT NULL,
    previous_route_id BIGINT,
    has_overflow BOOLEAN NOT NULL DEFAULT false,
    overflow_route_id BIGINT,
    provider_change_log_id BIGINT,
    changed_at TIMESTAMPTZ,
    changed_by BIGINT,
    reason TEXT,
    comment TEXT,
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_by BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_by BIGINT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_server_route_priorities_country FOREIGN KEY (country_id) REFERENCES countries(id) ON DELETE RESTRICT,
    CONSTRAINT fk_server_route_priorities_server FOREIGN KEY (server_id) REFERENCES servers(id) ON DELETE RESTRICT,
    CONSTRAINT fk_server_route_priorities_current_route FOREIGN KEY (current_route_id) REFERENCES routes(id) ON DELETE RESTRICT,
    CONSTRAINT fk_server_route_priorities_previous_route FOREIGN KEY (previous_route_id) REFERENCES routes(id) ON DELETE RESTRICT,
    CONSTRAINT fk_server_route_priorities_overflow_route FOREIGN KEY (overflow_route_id) REFERENCES routes(id) ON DELETE RESTRICT,
    CONSTRAINT fk_server_route_priorities_log FOREIGN KEY (provider_change_log_id) REFERENCES provider_change_logs(id) ON DELETE RESTRICT,
    CONSTRAINT fk_server_route_priorities_changed_by FOREIGN KEY (changed_by) REFERENCES users(id) ON DELETE RESTRICT,
    CONSTRAINT fk_server_route_priorities_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE RESTRICT,
    CONSTRAINT fk_server_route_priorities_updated_by FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE RESTRICT,
    CONSTRAINT uq_server_route_priorities_country_server UNIQUE (country_id, server_id)
);

CREATE TABLE IF NOT EXISTS routing_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_at TIMESTAMPTZ NOT NULL,
    apply_scope TEXT NOT NULL,
    reason TEXT NOT NULL,
    country_id BIGINT,
    server_id BIGINT,
    provider_id BIGINT,
    affected_route_id BIGINT,
    old_route_id BIGINT,
    new_route_id BIGINT,
    calling_company_id BIGINT,
    company_change_type TEXT,
    old_company_routing_mode TEXT,
    new_company_routing_mode TEXT,
    old_company_route_id BIGINT,
    new_company_route_id BIGINT,
    old_company_has_autorotation BOOLEAN,
    new_company_has_autorotation BOOLEAN,
    has_overflow BOOLEAN NOT NULL DEFAULT false,
    overflow_route_id BIGINT,
    comment TEXT NOT NULL,
    snapshot_json JSONB,
    is_active BOOLEAN NOT NULL DEFAULT true,
    deactivation_reason TEXT,
    deactivated_at TIMESTAMPTZ,
    deactivated_by BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by BIGINT NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_by BIGINT,
    CONSTRAINT fk_routing_events_country FOREIGN KEY (country_id) REFERENCES countries(id) ON DELETE RESTRICT,
    CONSTRAINT fk_routing_events_server FOREIGN KEY (server_id) REFERENCES servers(id) ON DELETE RESTRICT,
    CONSTRAINT fk_routing_events_provider FOREIGN KEY (provider_id) REFERENCES providers(id) ON DELETE RESTRICT,
    CONSTRAINT fk_routing_events_affected_route FOREIGN KEY (affected_route_id) REFERENCES routes(id) ON DELETE RESTRICT,
    CONSTRAINT fk_routing_events_old_route FOREIGN KEY (old_route_id) REFERENCES routes(id) ON DELETE RESTRICT,
    CONSTRAINT fk_routing_events_new_route FOREIGN KEY (new_route_id) REFERENCES routes(id) ON DELETE RESTRICT,
    CONSTRAINT fk_routing_events_company FOREIGN KEY (calling_company_id) REFERENCES calling_companies(id) ON DELETE RESTRICT,
    CONSTRAINT fk_routing_events_old_company_route FOREIGN KEY (old_company_route_id) REFERENCES routes(id) ON DELETE RESTRICT,
    CONSTRAINT fk_routing_events_new_company_route FOREIGN KEY (new_company_route_id) REFERENCES routes(id) ON DELETE RESTRICT,
    CONSTRAINT fk_routing_events_overflow_route FOREIGN KEY (overflow_route_id) REFERENCES routes(id) ON DELETE RESTRICT,
    CONSTRAINT fk_routing_events_deactivated_by FOREIGN KEY (deactivated_by) REFERENCES users(id) ON DELETE RESTRICT,
    CONSTRAINT fk_routing_events_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE RESTRICT,
    CONSTRAINT fk_routing_events_updated_by FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE RESTRICT,
    CONSTRAINT ck_routing_events_apply_scope CHECK (apply_scope IN ('none', 'server_priority', 'campaign_setting')),
    CONSTRAINT ck_routing_events_company_change_type CHECK (company_change_type IN ('enable_autorotation', 'disable_autorotation', 'set_campaign_route', 'remove_campaign_route') OR company_change_type IS NULL)
);

CREATE TABLE IF NOT EXISTS routing_event_servers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    routing_event_id BIGINT NOT NULL,
    server_id BIGINT NOT NULL,
    old_route_id BIGINT,
    new_route_id BIGINT NOT NULL,
    server_route_priority_id BIGINT,
    status TEXT NOT NULL DEFAULT 'applied',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_routing_event_servers_event FOREIGN KEY (routing_event_id) REFERENCES routing_events(id) ON DELETE RESTRICT,
    CONSTRAINT fk_routing_event_servers_server FOREIGN KEY (server_id) REFERENCES servers(id) ON DELETE RESTRICT,
    CONSTRAINT fk_routing_event_servers_old_route FOREIGN KEY (old_route_id) REFERENCES routes(id) ON DELETE RESTRICT,
    CONSTRAINT fk_routing_event_servers_new_route FOREIGN KEY (new_route_id) REFERENCES routes(id) ON DELETE RESTRICT,
    CONSTRAINT fk_routing_event_servers_priority FOREIGN KEY (server_route_priority_id) REFERENCES server_route_priorities(id) ON DELETE RESTRICT,
    CONSTRAINT ck_routing_event_servers_status CHECK (status IN ('applied', 'skipped_noop'))
);

CREATE TABLE IF NOT EXISTS change_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_type TEXT NOT NULL,
    entity_id BIGINT,
    change_type TEXT NOT NULL,
    changed_by BIGINT,
    changed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    old_values JSONB,
    new_values JSONB,
    summary TEXT,
    comment TEXT,
    source TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_change_log_changed_by FOREIGN KEY (changed_by) REFERENCES users(id) ON DELETE RESTRICT
);


CREATE TABLE IF NOT EXISTS hlr_daily_usage (
    usage_date DATE PRIMARY KEY,
    checked_count INTEGER NOT NULL DEFAULT 0,
    credits_spent NUMERIC(18,6),
    last_check_count INTEGER NOT NULL DEFAULT 0,
    last_check_credits NUMERIC(18,6),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_hlr_daily_usage_checked_count_nonnegative CHECK (checked_count >= 0),
    CONSTRAINT ck_hlr_daily_usage_last_check_count_nonnegative CHECK (last_check_count >= 0)
);

CREATE TABLE IF NOT EXISTS app_settings (
    key TEXT PRIMARY KEY,
    value TEXT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_by BIGINT,
    CONSTRAINT fk_app_settings_updated_by FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS import_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_type TEXT NOT NULL,
    mode TEXT NOT NULL,
    file_name TEXT NOT NULL,
    status TEXT NOT NULL,
    total_rows INTEGER,
    new_rows INTEGER,
    duplicate_rows INTEGER,
    skipped_rows INTEGER,
    updated_rows INTEGER,
    replaced_rows INTEGER,
    error_rows INTEGER,
    preview_data JSONB,
    summary JSONB,
    error_report JSONB,
    created_by BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    started_at TIMESTAMPTZ,
    finished_at TIMESTAMPTZ,
    CONSTRAINT fk_import_jobs_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE RESTRICT,
    CONSTRAINT ck_import_jobs_entity_type CHECK (entity_type IN ('routes', 'tariffs', 'phone_numbers', 'calling_companies', 'dictionaries')),
    CONSTRAINT ck_import_jobs_mode CHECK (mode IN ('append_update', 'replace_section')),
    CONSTRAINT ck_import_jobs_status CHECK (status IN ('draft', 'previewed', 'running', 'completed', 'failed', 'cancelled'))
);

CREATE TABLE IF NOT EXISTS api_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    token_hash TEXT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_by BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_used_at TIMESTAMPTZ,
    comment TEXT,
    CONSTRAINT uq_api_tokens_name UNIQUE (name),
    CONSTRAINT fk_api_tokens_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS telegram_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    is_enabled BOOLEAN NOT NULL DEFAULT false,
    chat_id TEXT,
    bot_token_secret_ref TEXT,
    message_template TEXT,
    last_test_status TEXT,
    last_test_at TIMESTAMPTZ,
    last_test_by BIGINT,
    last_test_error TEXT,
    updated_by BIGINT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_telegram_settings_last_test_by FOREIGN KEY (last_test_by) REFERENCES users(id) ON DELETE RESTRICT,
    CONSTRAINT fk_telegram_settings_updated_by FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE RESTRICT,
    CONSTRAINT ck_telegram_settings_last_test_status CHECK (last_test_status IN ('success', 'failed') OR last_test_status IS NULL)
);

CREATE INDEX IF NOT EXISTS idx_routes_country_id ON routes(country_id);
CREATE INDEX IF NOT EXISTS idx_routes_provider_id ON routes(provider_id);
CREATE INDEX IF NOT EXISTS idx_routes_name ON routes(name);
CREATE INDEX IF NOT EXISTS idx_routes_is_actual ON routes(is_actual);
CREATE INDEX IF NOT EXISTS idx_tariffs_country_id ON tariffs(country_id);
CREATE INDEX IF NOT EXISTS idx_tariffs_provider_id ON tariffs(provider_id);
CREATE INDEX IF NOT EXISTS idx_tariffs_is_current ON tariffs(is_current);
CREATE INDEX IF NOT EXISTS idx_phone_numbers_country_id ON phone_numbers(country_id);
CREATE INDEX IF NOT EXISTS idx_phone_numbers_provider_id ON phone_numbers(provider_id);
CREATE INDEX IF NOT EXISTS idx_phone_numbers_status ON phone_numbers(status);
CREATE INDEX IF NOT EXISTS idx_phone_numbers_assignment_type ON phone_numbers(assignment_type);
CREATE INDEX IF NOT EXISTS idx_phone_numbers_number ON phone_numbers(number);
CREATE INDEX IF NOT EXISTS idx_route_phone_numbers_route_id ON route_phone_numbers(route_id);
CREATE INDEX IF NOT EXISTS idx_route_phone_numbers_phone_number_id ON route_phone_numbers(phone_number_id);
CREATE INDEX IF NOT EXISTS idx_provider_change_logs_changed_at ON provider_change_logs(changed_at);
CREATE INDEX IF NOT EXISTS idx_provider_change_logs_country_id ON provider_change_logs(country_id);
CREATE INDEX IF NOT EXISTS idx_calling_companies_server_id ON calling_companies(server_id);
CREATE INDEX IF NOT EXISTS idx_calling_companies_country_id ON calling_companies(country_id);
CREATE INDEX IF NOT EXISTS idx_calling_companies_external_id ON calling_companies(company_id_external);
CREATE INDEX IF NOT EXISTS idx_company_routing_settings_company_id ON company_routing_settings(calling_company_id);
CREATE INDEX IF NOT EXISTS idx_company_routing_settings_country_id ON company_routing_settings(country_id);
CREATE INDEX IF NOT EXISTS idx_company_routing_settings_server_id ON company_routing_settings(server_id);
CREATE INDEX IF NOT EXISTS idx_company_routing_settings_route_id ON company_routing_settings(route_id);
CREATE UNIQUE INDEX IF NOT EXISTS ux_company_routing_settings_one_active ON company_routing_settings(calling_company_id) WHERE is_active IS TRUE AND valid_to IS NULL;
CREATE INDEX IF NOT EXISTS idx_server_route_priorities_country_id ON server_route_priorities(country_id);
CREATE INDEX IF NOT EXISTS idx_server_route_priorities_server_id ON server_route_priorities(server_id);
CREATE INDEX IF NOT EXISTS idx_routing_events_event_at ON routing_events(event_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS idx_routing_events_scope ON routing_events(apply_scope);
CREATE INDEX IF NOT EXISTS idx_routing_events_active ON routing_events(is_active);
CREATE INDEX IF NOT EXISTS idx_routing_event_servers_event ON routing_event_servers(routing_event_id);
CREATE INDEX IF NOT EXISTS idx_routing_event_servers_server ON routing_event_servers(server_id);
CREATE INDEX IF NOT EXISTS idx_routing_event_servers_new_route ON routing_event_servers(new_route_id);
CREATE INDEX IF NOT EXISTS idx_change_log_changed_at ON change_log(changed_at);
CREATE INDEX IF NOT EXISTS idx_change_log_entity ON change_log(entity_type, entity_id);
