import json
import sqlite3
import tempfile
import unittest
from pathlib import Path

from scripts import postgres_preflight


SCHEMA_SQL = """
CREATE TABLE IF NOT EXISTS users (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, username TEXT NOT NULL, must_change_password BOOLEAN NOT NULL, is_active BOOLEAN NOT NULL, created_at TIMESTAMPTZ NOT NULL, password_hash TEXT);
CREATE TABLE IF NOT EXISTS change_log (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, changed_by BIGINT, old_values JSONB, new_values JSONB, changed_at TIMESTAMPTZ NOT NULL);
"""


class PostgresPreflightTests(unittest.TestCase):
    def make_db(self, ddl, rows=()):
        tmp = tempfile.TemporaryDirectory()
        db_path = Path(tmp.name) / "preflight.sqlite3"
        schema_path = Path(tmp.name) / "schema.postgres.sql"
        schema_path.write_text(SCHEMA_SQL, encoding="utf-8")
        conn = sqlite3.connect(db_path)
        try:
            conn.executescript(ddl)
            for sql, params in rows:
                conn.execute(sql, params)
            conn.commit()
        finally:
            conn.close()
        self.addCleanup(tmp.cleanup)
        return db_path, schema_path

    def test_preflight_opens_database_read_only(self):
        db_path, schema_path = self.make_db("CREATE TABLE users (id INTEGER PRIMARY KEY, username TEXT, is_active INTEGER, must_change_password INTEGER, created_at TEXT)")
        report = postgres_preflight.run_preflight(db_path, schema_path)
        self.assertGreaterEqual(report.info_count, 1)
        with sqlite3.connect(f"file:{db_path}?mode=ro", uri=True) as conn:
            with self.assertRaises(sqlite3.OperationalError):
                conn.execute("CREATE TABLE should_fail (id INTEGER)")

    def test_preflight_detects_duplicate_business_key(self):
        db_path, schema_path = self.make_db(
            "CREATE TABLE users (id INTEGER PRIMARY KEY, username TEXT, is_active INTEGER, must_change_password INTEGER, created_at TEXT)",
            [
                ("INSERT INTO users VALUES (?, ?, ?, ?, ?)", (1, "dupe", 1, 0, "2026-01-01 10:00:00")),
                ("INSERT INTO users VALUES (?, ?, ?, ?, ?)", (2, "dupe", 1, 0, "2026-01-01 10:00:00")),
            ],
        )
        report = postgres_preflight.run_preflight(db_path, schema_path)
        self.assertTrue(any(r.level == "error" and r.check == "duplicate_business_key" and r.table == "users" for r in report.results))

    def test_preflight_detects_invalid_boolean(self):
        db_path, schema_path = self.make_db(
            "CREATE TABLE users (id INTEGER PRIMARY KEY, username TEXT, is_active INTEGER NOT NULL, must_change_password INTEGER NOT NULL, created_at TEXT)",
            [("INSERT INTO users VALUES (?, ?, ?, ?, ?)", (1, "alice", 2, 0, "2026-01-01 10:00:00"))],
        )
        report = postgres_preflight.run_preflight(db_path, schema_path)
        self.assertTrue(any(r.check == "boolean_values" and r.table == "users" and r.column == "is_active" for r in report.results))

    def test_preflight_detects_invalid_timestamp(self):
        db_path, schema_path = self.make_db(
            "CREATE TABLE users (id INTEGER PRIMARY KEY, username TEXT, is_active INTEGER, must_change_password INTEGER, created_at TEXT NOT NULL)",
            [("INSERT INTO users VALUES (?, ?, ?, ?, ?)", (1, "alice", 1, 0, "not-a-date"))],
        )
        report = postgres_preflight.run_preflight(db_path, schema_path)
        self.assertTrue(any(r.check == "timestamp_values" and r.table == "users" and r.column == "created_at" for r in report.results))

    def test_preflight_detects_invalid_json(self):
        db_path, schema_path = self.make_db(
            "CREATE TABLE change_log (id INTEGER PRIMARY KEY, changed_by INTEGER, old_values TEXT, new_values TEXT, changed_at TEXT)",
            [("INSERT INTO change_log VALUES (?, ?, ?, ?, ?)", (1, None, '{bad json', '{"ok": true}', "2026-01-01 10:00:00"))],
        )
        report = postgres_preflight.run_preflight(db_path, schema_path)
        self.assertTrue(any(r.level == "error" and r.check == "json_values" and r.table == "change_log" and r.column == "old_values" for r in report.results))

    def test_preflight_masks_sensitive_values(self):
        masked = postgres_preflight.safe_value("password_hash", "super-secret-password-token")
        self.assertEqual(masked, "***MASKED***")
        preview = postgres_preflight.safe_value("new_values", '{"token":"abc123secret", "safe":"ok"}')
        self.assertNotIn("abc123secret", preview)
        self.assertIn("***MASKED***", preview)

    def test_preflight_has_no_postgres_dependency(self):
        source = Path(postgres_preflight.__file__).read_text(encoding="utf-8")
        self.assertNotIn("psycopg", source)
        self.assertNotIn("import psycopg", source)
        self.assertNotIn("from psycopg", source)


if __name__ == "__main__":
    unittest.main()
