from pathlib import Path
import unittest


REPO_ROOT = Path(__file__).resolve().parents[1]
POSTGRES_SCHEMA = REPO_ROOT / "docs" / "postgres" / "schema.postgres.sql"
SQLITE_SCHEMA = REPO_ROOT / "app" / "schema.sql"
OPTIONAL_CAMPAIGN_GEO_MIGRATION = REPO_ROOT / "docs/postgres/migrations/0069l_optional_campaign_geo.sql"
NULLABLE_ROUTING_GEO_MIGRATION = REPO_ROOT / "docs/postgres/migrations/0069m_nullable_routing_setting_geo.sql"


class PostgresSchemaDraftTests(unittest.TestCase):
    def test_schema_draft_exists(self):
        self.assertTrue(POSTGRES_SCHEMA.exists())

    def test_schema_draft_has_no_sqlite_specific_syntax(self):
        sql = POSTGRES_SCHEMA.read_text(encoding="utf-8")
        forbidden = [
            "AUTOINCREMENT",
            "PRAGMA",
            "GLOB",
            "sqlite_master",
            "INSERT OR IGNORE",
            "INSERT OR REPLACE",
            "json_extract",
            "datetime(",
        ]
        for token in forbidden:
            with self.subTest(token=token):
                self.assertNotIn(token, sql)

    def test_schema_draft_contains_postgres_primitives(self):
        sql = POSTGRES_SCHEMA.read_text(encoding="utf-8")
        required = [
            "GENERATED BY DEFAULT AS IDENTITY",
            "BOOLEAN",
            "TIMESTAMPTZ",
            "JSONB",
            "CREATE INDEX",
        ]
        for token in required:
            with self.subTest(token=token):
                self.assertIn(token, sql)

    def test_sqlite_schema_still_exists_as_runtime_schema(self):
        sql = SQLITE_SCHEMA.read_text(encoding="utf-8")
        self.assertIn("PRAGMA foreign_keys = ON;", sql)
        self.assertIn("CREATE TABLE IF NOT EXISTS users", sql)
        self.assertIn("INTEGER PRIMARY KEY AUTOINCREMENT", sql)

    def test_optional_campaign_geo_schema_and_migration_contract(self):
        schema = POSTGRES_SCHEMA.read_text(encoding="utf-8")
        migration = OPTIONAL_CAMPAIGN_GEO_MIGRATION.read_text(encoding="utf-8")
        calling_company = schema.split("CREATE TABLE IF NOT EXISTS calling_companies", 1)[1].split(");", 1)[0]
        routing_setting = schema.split("CREATE TABLE IF NOT EXISTS company_routing_settings", 1)[1].split(");", 1)[0]

        self.assertIn("country_id BIGINT,", calling_company)
        self.assertNotIn("country_id BIGINT NOT NULL", calling_company)
        self.assertIn("FOREIGN KEY (country_id) REFERENCES countries(id)", calling_company)
        self.assertIn("country_id BIGINT,", routing_setting)
        self.assertNotIn("country_id BIGINT NOT NULL", routing_setting)
        self.assertIn("ALTER TABLE calling_companies ALTER COLUMN country_id DROP NOT NULL", migration)
        self.assertNotIn("ALTER TABLE calling_companies ALTER COLUMN country_id DROP NOT NULL", schema)
        self.assertIn("CREATE UNIQUE INDEX IF NOT EXISTS ux_calling_companies_multi_geo_identity", migration)

        routing_migration = NULLABLE_ROUTING_GEO_MIGRATION.read_text(encoding="utf-8")
        self.assertIn("ALTER TABLE company_routing_settings", routing_migration)
        self.assertIn("ALTER COLUMN country_id DROP NOT NULL", routing_migration)
        self.assertNotIn("DROP CONSTRAINT", routing_migration)


if __name__ == "__main__":
    unittest.main()
