import io
import sqlite3
import tempfile
import unittest
from contextlib import redirect_stdout
from datetime import date, datetime
from decimal import Decimal
from pathlib import Path

from scripts import migrate_sqlite_to_postgres as mig

REPO_ROOT = Path(__file__).resolve().parents[1]
SCHEMA = REPO_ROOT / "docs" / "postgres" / "schema.postgres.sql"


class SqliteToPostgresMigrationTests(unittest.TestCase):
    def make_db(self, ddl="CREATE TABLE users (id INTEGER PRIMARY KEY, username TEXT)"):
        tmp = tempfile.TemporaryDirectory()
        db_path = Path(tmp.name) / "test.sqlite3"
        conn = sqlite3.connect(db_path)
        conn.executescript(ddl)
        conn.commit()
        conn.close()
        self.addCleanup(tmp.cleanup)
        return db_path

    def test_migration_order_covers_schema_tables(self):
        pg_tables = set(mig.parse_create_table_columns(SCHEMA.read_text(encoding="utf-8")))
        missing = pg_tables - set(mig.MIGRATION_ORDER) - mig.SCHEMA_ONLY_TABLES
        self.assertEqual(set(), missing)
        self.assertEqual(35, len(mig.MIGRATION_ORDER))

    def test_sqlite_readonly_open(self):
        db_path = self.make_db()
        conn = mig.open_sqlite_readonly(db_path)
        self.addCleanup(conn.close)
        with self.assertRaises(sqlite3.OperationalError):
            conn.execute("INSERT INTO users (username) VALUES ('blocked')")

    def test_dry_run_without_postgres_dependency(self):
        db_path = self.make_db()
        schema_path = Path(tempfile.mkdtemp()) / "schema.sql"
        self.addCleanup(lambda: schema_path.unlink(missing_ok=True))
        schema_path.write_text("CREATE TABLE IF NOT EXISTS users (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, username TEXT);", encoding="utf-8")
        original_order = mig.MIGRATION_ORDER[:]
        try:
            mig.MIGRATION_ORDER[:] = ["users"]
            out = io.StringIO()
            with redirect_stdout(out):
                code = mig.run(["--sqlite-db", str(db_path), "--schema", str(schema_path), "--dry-run"])
            self.assertEqual(0, code, out.getvalue())
            self.assertIn("Ready for --apply", out.getvalue())
        finally:
            mig.MIGRATION_ORDER[:] = original_order

    def test_boolean_conversion(self):
        self.assertIs(mig.convert_boolean(0), False)
        self.assertIs(mig.convert_boolean(1), True)
        self.assertIsNone(mig.convert_boolean(None))

    def test_date_conversion(self):
        self.assertEqual(date(2026, 7, 12), mig.convert_date("2026-07-12"))

    def test_timestamp_conversion(self):
        self.assertEqual(datetime(2026, 7, 12, 10, 11, 12), mig.convert_timestamp("2026-07-12 10:11:12"))
        self.assertEqual(datetime(2026, 7, 12, 10, 11, 12), mig.convert_timestamp("2026-07-12T10:11:12"))

    def test_numeric_conversion(self):
        self.assertEqual(Decimal("12.3400"), mig.convert_numeric("12.3400"))
        with self.assertRaises(mig.MigrationError):
            mig.convert_numeric("")

    def test_jsonb_conversion(self):
        self.assertEqual({"a": [1]}, mig.convert_jsonb('{"a":[1]}'))
        self.assertIsNone(mig.convert_jsonb(None))
        with self.assertRaises(mig.MigrationError):
            mig.convert_jsonb("{bad")

    def test_no_id_table_supported(self):
        db_path = self.make_db("""
            CREATE TABLE app_settings (key TEXT PRIMARY KEY, value TEXT);
            CREATE TABLE hlr_daily_usage (usage_date TEXT PRIMARY KEY, checked_count INTEGER);
            CREATE TABLE demo_data_state (key TEXT PRIMARY KEY, value TEXT);
        """)
        schema = Path(tempfile.mkdtemp()) / "schema.sql"
        self.addCleanup(lambda: schema.unlink(missing_ok=True))
        schema.write_text("""
            CREATE TABLE IF NOT EXISTS app_settings (key TEXT PRIMARY KEY, value TEXT);
            CREATE TABLE IF NOT EXISTS hlr_daily_usage (usage_date DATE PRIMARY KEY, checked_count INTEGER);
            CREATE TABLE IF NOT EXISTS demo_data_state (key TEXT PRIMARY KEY, value TEXT);
        """, encoding="utf-8")
        original_order = mig.MIGRATION_ORDER[:]
        try:
            mig.MIGRATION_ORDER[:] = ["app_settings", "hlr_daily_usage", "demo_data_state"]
            conn = mig.open_sqlite_readonly(db_path)
            self.addCleanup(conn.close)
            plan = mig.build_plan(conn, schema)
            self.assertEqual([False, False, False], [p.has_id for p in plan])
        finally:
            mig.MIGRATION_ORDER[:] = original_order

    def test_sequence_reset_sql_only_for_id_tables(self):
        plan = [mig.TablePlan("users", ["id"], ["id"], ["id"], True), mig.TablePlan("app_settings", ["key"], ["key"], ["key"], False)]
        self.assertEqual(["users"], mig.sequence_reset_tables(plan))
        self.assertIn("pg_get_serial_sequence('users', 'id')", mig.sequence_reset_sql("users"))

    def test_postgres_url_masking(self):
        masked = mig.mask_postgres_url("postgresql://user:secret@localhost:5432/teleroute?sslmode=require")
        self.assertIn("user:***@localhost:5432/teleroute", masked)
        self.assertNotIn("secret", masked)
        self.assertNotIn("sslmode", masked)


if __name__ == "__main__":
    unittest.main()
