from pathlib import Path
import unittest


REPO_ROOT = Path(__file__).resolve().parents[1]
POSTGRES_SCHEMA = REPO_ROOT / "docs" / "postgres" / "schema.postgres.sql"
SQLITE_SCHEMA = REPO_ROOT / "app" / "schema.sql"


class PostgresSchemaDraftTests(unittest.TestCase):
    def test_schema_draft_exists(self):
        self.assertTrue(POSTGRES_SCHEMA.exists())

    def test_schema_draft_has_no_sqlite_specific_syntax(self):
        sql = POSTGRES_SCHEMA.read_text(encoding="utf-8")
        forbidden = [
            "AUTOINCREMENT",
            "PRAGMA",
            "GLOB",
            "sqlite_master",
            "INSERT OR IGNORE",
            "INSERT OR REPLACE",
            "json_extract",
            "datetime(",
        ]
        for token in forbidden:
            with self.subTest(token=token):
                self.assertNotIn(token, sql)

    def test_schema_draft_contains_postgres_primitives(self):
        sql = POSTGRES_SCHEMA.read_text(encoding="utf-8")
        required = [
            "GENERATED BY DEFAULT AS IDENTITY",
            "BOOLEAN",
            "TIMESTAMPTZ",
            "JSONB",
            "CREATE INDEX",
        ]
        for token in required:
            with self.subTest(token=token):
                self.assertIn(token, sql)

    def test_sqlite_schema_still_exists_as_runtime_schema(self):
        sql = SQLITE_SCHEMA.read_text(encoding="utf-8")
        self.assertIn("PRAGMA foreign_keys = ON;", sql)
        self.assertIn("CREATE TABLE IF NOT EXISTS users", sql)
        self.assertIn("INTEGER PRIMARY KEY AUTOINCREMENT", sql)


if __name__ == "__main__":
    unittest.main()
