import json
import sqlite3
import tempfile
import unittest
from pathlib import Path

from scripts import postgres_preflight


SCHEMA_SQL = """
CREATE TABLE IF NOT EXISTS users (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, username TEXT NOT NULL, must_change_password BOOLEAN NOT NULL, is_active BOOLEAN NOT NULL, created_at TIMESTAMPTZ NOT NULL, password_hash TEXT);
CREATE TABLE IF NOT EXISTS change_log (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, changed_by BIGINT, old_values JSONB, new_values JSONB, changed_at TIMESTAMPTZ NOT NULL);
"""


class PostgresPreflightTests(unittest.TestCase):
    def make_db(self, ddl, rows=()):
        tmp = tempfile.TemporaryDirectory()
        db_path = Path(tmp.name) / "preflight.sqlite3"
        schema_path = Path(tmp.name) / "schema.postgres.sql"
        schema_path.write_text(SCHEMA_SQL, encoding="utf-8")
        conn = sqlite3.connect(db_path)
        try:
            conn.executescript(ddl)
            for sql, params in rows:
                conn.execute(sql, params)
            conn.commit()
        finally:
            conn.close()
        self.addCleanup(tmp.cleanup)
        return db_path, schema_path

    def test_preflight_opens_database_read_only(self):
        db_path, schema_path = self.make_db("CREATE TABLE users (id INTEGER PRIMARY KEY, username TEXT, is_active INTEGER, must_change_password INTEGER, created_at TEXT)")
        report = postgres_preflight.run_preflight(db_path, schema_path)
        self.assertGreaterEqual(report.info_count, 1)
        with sqlite3.connect(f"file:{db_path}?mode=ro", uri=True) as conn:
            with self.assertRaises(sqlite3.OperationalError):
                conn.execute("CREATE TABLE should_fail (id INTEGER)")

    def test_preflight_detects_duplicate_business_key(self):
        db_path, schema_path = self.make_db(
            "CREATE TABLE users (id INTEGER PRIMARY KEY, username TEXT, is_active INTEGER, must_change_password INTEGER, created_at TEXT)",
            [
                ("INSERT INTO users VALUES (?, ?, ?, ?, ?)", (1, "dupe", 1, 0, "2026-01-01 10:00:00")),
                ("INSERT INTO users VALUES (?, ?, ?, ?, ?)", (2, "dupe", 1, 0, "2026-01-01 10:00:00")),
            ],
        )
        report = postgres_preflight.run_preflight(db_path, schema_path)
        self.assertTrue(any(r.level == "error" and r.check == "duplicate_business_key" and r.table == "users" for r in report.results))

    def test_preflight_detects_invalid_boolean(self):
        db_path, schema_path = self.make_db(
            "CREATE TABLE users (id INTEGER PRIMARY KEY, username TEXT, is_active INTEGER NOT NULL, must_change_password INTEGER NOT NULL, created_at TEXT)",
            [("INSERT INTO users VALUES (?, ?, ?, ?, ?)", (1, "alice", 2, 0, "2026-01-01 10:00:00"))],
        )
        report = postgres_preflight.run_preflight(db_path, schema_path)
        self.assertTrue(any(r.check == "boolean_values" and r.table == "users" and r.column == "is_active" for r in report.results))

    def test_preflight_detects_invalid_timestamp(self):
        db_path, schema_path = self.make_db(
            "CREATE TABLE users (id INTEGER PRIMARY KEY, username TEXT, is_active INTEGER, must_change_password INTEGER, created_at TEXT NOT NULL)",
            [("INSERT INTO users VALUES (?, ?, ?, ?, ?)", (1, "alice", 1, 0, "not-a-date"))],
        )
        report = postgres_preflight.run_preflight(db_path, schema_path)
        self.assertTrue(any(r.check == "timestamp_values" and r.table == "users" and r.column == "created_at" for r in report.results))

    def test_preflight_detects_invalid_json(self):
        db_path, schema_path = self.make_db(
            "CREATE TABLE change_log (id INTEGER PRIMARY KEY, changed_by INTEGER, old_values TEXT, new_values TEXT, changed_at TEXT)",
            [("INSERT INTO change_log VALUES (?, ?, ?, ?, ?)", (1, None, '{bad json', '{"ok": true}', "2026-01-01 10:00:00"))],
        )
        report = postgres_preflight.run_preflight(db_path, schema_path)
        self.assertTrue(any(r.level == "error" and r.check == "json_values" and r.table == "change_log" and r.column == "old_values" for r in report.results))

    def test_preflight_masks_sensitive_values(self):
        masked = postgres_preflight.safe_value("password_hash", "super-secret-password-token")
        self.assertEqual(masked, "***MASKED***")
        preview = postgres_preflight.safe_value("new_values", '{"token":"abc123secret", "safe":"ok"}')
        self.assertNotIn("abc123secret", preview)
        self.assertIn("***MASKED***", preview)


    def test_rate_date_is_checked_as_date_not_numeric(self):
        db_path, schema_path = self.make_db(
            "CREATE TABLE currency_rates (id INTEGER PRIMARY KEY, rate_date TEXT NOT NULL, rate_to_eur TEXT)",
            [("INSERT INTO currency_rates VALUES (?, ?, ?)", (1, "2026-07-12", "1.25"))],
        )
        report = postgres_preflight.run_preflight(db_path, schema_path)
        self.assertFalse(any(r.check == "numeric_values" and r.table == "currency_rates" and r.column == "rate_date" for r in report.results))
        self.assertFalse(any(r.check == "date_values" and r.table == "currency_rates" and r.column == "rate_date" for r in report.results))

    def test_conversion_rate_date_is_checked_as_date_not_numeric(self):
        db_path, schema_path = self.make_db(
            """
            CREATE TABLE tariffs (id INTEGER PRIMARY KEY, conversion_rate_date TEXT NOT NULL);
            CREATE TABLE tariff_change_history (id INTEGER PRIMARY KEY, old_conversion_rate_date TEXT, new_conversion_rate_date TEXT NOT NULL);
            """,
            [
                ("INSERT INTO tariffs VALUES (?, ?)", (1, "2026-07-02")),
                ("INSERT INTO tariff_change_history VALUES (?, ?, ?)", (1, "2026-06-07", "2026-07-12")),
            ],
        )
        report = postgres_preflight.run_preflight(db_path, schema_path)
        date_columns = {"conversion_rate_date", "old_conversion_rate_date", "new_conversion_rate_date"}
        self.assertFalse(any(r.check == "numeric_values" and r.column in date_columns for r in report.results))
        self.assertFalse(any(r.check == "date_values" and r.column in date_columns for r in report.results))

    def test_route_history_plain_text_is_allowed_when_target_text(self):
        db_path, schema_path = self.make_db(
            "CREATE TABLE route_history (id INTEGER PRIMARY KEY, route_id INTEGER, new_value TEXT)",
            [("INSERT INTO route_history VALUES (?, ?, ?)", (1, 10, "Мексика/Sancom/Demo_0827@"))],
        )
        report = postgres_preflight.run_preflight(db_path, schema_path)
        self.assertFalse(any(r.check == "json_values" and r.table == "route_history" and r.column == "new_value" for r in report.results))

    def test_demo_data_state_is_in_postgres_schema_or_explicitly_ignored(self):
        schema = (Path(__file__).resolve().parents[1] / "docs" / "postgres" / "schema.postgres.sql").read_text(encoding="utf-8")
        decisions = (Path(__file__).resolve().parents[1] / "docs" / "postgres" / "schema_decisions.md").read_text(encoding="utf-8")
        self.assertTrue("CREATE TABLE IF NOT EXISTS demo_data_state" in schema or "demo_data_state" in decisions and "ignored" in decisions.lower())

    def test_preflight_has_no_postgres_dependency(self):
        source = Path(postgres_preflight.__file__).read_text(encoding="utf-8")
        self.assertNotIn("psycopg", source)
        self.assertNotIn("import psycopg", source)
        self.assertNotIn("from psycopg", source)

    def test_preflight_handles_table_without_id(self):
        db_path, schema_path = self.make_db(
            "CREATE TABLE app_settings (key TEXT PRIMARY KEY, value TEXT, updated_at TEXT)",
            [("INSERT INTO app_settings VALUES (?, ?, ?)", ("site_name", "TeleRoute", "2026-01-01 10:00:00"))],
        )
        report = postgres_preflight.run_preflight(db_path, schema_path)
        self.assertTrue(any(r.check == "table_inventory" and r.table == "app_settings" and "no id column" in r.message for r in report.results))

    def test_id_readiness_skips_table_without_id(self):
        db_path, schema_path = self.make_db(
            "CREATE TABLE app_settings (key TEXT PRIMARY KEY, value TEXT)",
            [("INSERT INTO app_settings VALUES (?, ?)", ("site_name", "TeleRoute"))],
        )
        report = postgres_preflight.run_preflight(db_path, schema_path)
        id_results = [r for r in report.results if r.check == "id_sequence_readiness" and r.table == "app_settings"]
        self.assertEqual(len(id_results), 1)
        self.assertEqual(id_results[0].level, "info")
        self.assertIn("has no id column", id_results[0].message)
        self.assertFalse(any(r.check == "id_sequence_readiness" and r.table == "app_settings" and r.column == "id" for r in report.results))

    def test_duplicate_samples_use_business_key_when_no_id(self):
        db_path, schema_path = self.make_db(
            "CREATE TABLE user_permissions (user_id INTEGER, section_key TEXT)",
            [
                ("INSERT INTO user_permissions VALUES (?, ?)", (1, "routes")),
                ("INSERT INTO user_permissions VALUES (?, ?)", (1, "routes")),
            ],
        )
        report = postgres_preflight.run_preflight(db_path, schema_path)
        duplicate = next(r for r in report.results if r.check == "duplicate_business_key" and r.table == "user_permissions")
        self.assertEqual(duplicate.sample_rows[0]["user_id"], "1")
        self.assertEqual(duplicate.sample_rows[0]["section_key"], "routes")
        self.assertNotIn("ids", duplicate.sample_rows[0])

    def test_preflight_realistic_schema_no_id_join_table(self):
        db_path, schema_path = self.make_db(
            "CREATE TABLE route_phone_numbers (route_id INTEGER, phone_number_id INTEGER, PRIMARY KEY (route_id, phone_number_id)) WITHOUT ROWID",
            [("INSERT INTO route_phone_numbers VALUES (?, ?)", (10, 20))],
        )
        report = postgres_preflight.run_preflight(db_path, schema_path)
        self.assertTrue(any(r.check == "id_sequence_readiness" and r.table == "route_phone_numbers" and r.level == "info" for r in report.results))
        self.assertFalse(any(r.level == "error" for r in report.results))


if __name__ == "__main__":
    unittest.main()
