-- Stage 69P1: managed provider-change reason scopes.
DO $$
DECLARE
    scopes_table_existed BOOLEAN := to_regclass('change_reason_scopes') IS NOT NULL;
BEGIN
    CREATE TABLE IF NOT EXISTS change_reason_scopes (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        reason_id BIGINT NOT NULL REFERENCES change_reasons(id) ON DELETE CASCADE,
        apply_scope TEXT NOT NULL CHECK (apply_scope IN ('none', 'server_priority', 'campaign_setting')),
        CONSTRAINT uq_change_reason_scopes_reason_scope UNIQUE (reason_id, apply_scope)
    );

    IF NOT scopes_table_existed THEN
        INSERT INTO change_reason_scopes(reason_id, apply_scope)
        SELECT reason.id, scope.apply_scope
        FROM change_reasons AS reason
        CROSS JOIN (VALUES ('none'), ('server_priority'), ('campaign_setting')) AS scope(apply_scope)
        ON CONFLICT (reason_id, apply_scope) DO NOTHING;
    END IF;
END $$;

WITH legacy(apply_scope, name) AS (
    VALUES
        ('none', 'Обновление/смена АОНов'), ('none', 'Провайдер сменил маршрут'), ('none', 'Другое'),
        ('server_priority', 'Массовый отбои/занято'), ('server_priority', 'Обратная смена провайдера'),
        ('server_priority', 'Задача руководства'), ('server_priority', 'Другое'),
        ('campaign_setting', 'Задача руководства'), ('campaign_setting', 'Массовые отбои / занято'),
        ('campaign_setting', 'Плохой дозвон'), ('campaign_setting', 'Провайдер не отвечает'),
        ('campaign_setting', 'Авария у провайдера'), ('campaign_setting', 'Тест нового маршрута'),
        ('campaign_setting', 'Плановое переключение'), ('campaign_setting', 'Обновление пула / АОН'),
        ('campaign_setting', 'Проблема с префиксом'), ('campaign_setting', 'Другое')
), inserted AS (
    INSERT INTO change_reasons(name, description, is_active)
    SELECT DISTINCT legacy.name, legacy.name, true
    FROM legacy
    WHERE NOT EXISTS (SELECT 1 FROM change_reasons reason WHERE lower(reason.name) = lower(legacy.name))
    RETURNING id
)
INSERT INTO change_reason_scopes(reason_id, apply_scope)
SELECT reason.id, legacy.apply_scope
FROM legacy
JOIN change_reasons reason ON lower(reason.name) = lower(legacy.name)
ON CONFLICT (reason_id, apply_scope) DO NOTHING;
