-- SPAM Checker V1: manual Telegram batches, immutable results and current score.
CREATE TABLE IF NOT EXISTS spam_check_batches (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 request_token TEXT NOT NULL UNIQUE,
 source TEXT NOT NULL DEFAULT 'telegram_manual',
 selection_mode TEXT NOT NULL,
 raw_response TEXT NOT NULL,
 checked_by BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
 created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
 parser_version TEXT NOT NULL,
 requested_count INTEGER NOT NULL,
 CONSTRAINT ck_spam_batch_mode CHECK (selection_mode IN ('phones','routes'))
);
CREATE TABLE IF NOT EXISTS phone_spam_state (
 phone_number_id BIGINT PRIMARY KEY REFERENCES phone_numbers(id) ON DELETE RESTRICT,
 score SMALLINT NOT NULL DEFAULT 0 CHECK (score BETWEEN 0 AND 5),
 last_checked_at TIMESTAMPTZ,
 last_verdict TEXT,
 last_source TEXT,
 updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS spam_check_results (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 batch_id BIGINT NOT NULL REFERENCES spam_check_batches(id) ON DELETE RESTRICT,
 phone_number_id BIGINT NOT NULL REFERENCES phone_numbers(id) ON DELETE RESTRICT,
 verdict TEXT NOT NULL CHECK (verdict IN ('spam','clear')),
 source TEXT,
 severity TEXT NOT NULL CHECK (severity IN ('soft','strong','clear')),
 sources_json JSONB NOT NULL DEFAULT '[]'::jsonb,
 score_before SMALLINT NOT NULL CHECK (score_before BETWEEN 0 AND 5),
 score_delta SMALLINT NOT NULL,
 score_after SMALLINT NOT NULL CHECK (score_after BETWEEN 0 AND 5),
 checked_at TIMESTAMPTZ NOT NULL DEFAULT now(),
 created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
 UNIQUE(batch_id, phone_number_id)
);
CREATE TABLE IF NOT EXISTS spam_check_result_routes (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 result_id BIGINT NOT NULL REFERENCES spam_check_results(id) ON DELETE RESTRICT,
 route_id BIGINT REFERENCES routes(id) ON DELETE SET NULL,
 route_name_snapshot TEXT NOT NULL,
 UNIQUE(result_id, route_id)
);
CREATE INDEX IF NOT EXISTS idx_spam_results_phone_checked ON spam_check_results(phone_number_id, checked_at DESC);
CREATE INDEX IF NOT EXISTS idx_spam_results_batch ON spam_check_results(batch_id);
CREATE INDEX IF NOT EXISTS idx_phone_spam_state_score ON phone_spam_state(score);
CREATE INDEX IF NOT EXISTS idx_phone_spam_state_last_checked ON phone_spam_state(last_checked_at);
CREATE INDEX IF NOT EXISTS idx_spam_result_routes_result ON spam_check_result_routes(result_id);
CREATE INDEX IF NOT EXISTS idx_spam_result_routes_route ON spam_check_result_routes(route_id);
