BEGIN;

CREATE TABLE routing_event_routes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    routing_event_id BIGINT NOT NULL REFERENCES routing_events(id) ON DELETE RESTRICT,
    route_id BIGINT NOT NULL REFERENCES routes(id) ON DELETE RESTRICT,
    route_name TEXT NOT NULL,
    provider_name TEXT NOT NULL,
    position INTEGER NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (routing_event_id, route_id),
    UNIQUE (routing_event_id, position)
);

CREATE INDEX idx_routing_event_routes_event ON routing_event_routes(routing_event_id);
CREATE INDEX idx_routing_event_routes_route ON routing_event_routes(route_id);

-- Preserve the existing single-route association as the first member.
INSERT INTO routing_event_routes(routing_event_id, route_id, route_name, provider_name, position)
SELECT re.id, r.id, r.name, p.name, 0
FROM routing_events re
JOIN routes r ON r.id = re.affected_route_id
JOIN providers p ON p.id = r.provider_id
WHERE re.apply_scope = 'none';

COMMIT;
